modLoader="javafml"
loaderVersion="[47,)"
license="GNU General Public License version 3 (GPLv3)"
[[mods]]
modId="reputationmod"
version="1.3"
displayName="REP"

logoFile="rep_pfp.png"
logoBlur=false

authors="Kubik"

description='''REP introduces a dynamic reputation system to Minecraft, where player actions influence their standing in the world, affecting mob behavior, villager interactions, and environmental responses.'''
[[dependencies.reputationmod]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.reputationmod]]
modId="minecraft"
mandatory=true
versionRange="[1.20, 1.21)"
ordering="NONE"
side="BOTH"